package main

// "name of command":"tag_on_gelbooru"
var characters = map[string]string{
	// Touhou
	"reimu":        "hakurei_reimu",
	"marisa":       "kirisame_marisa",
	"youmu":        "konpaku_youmu", // :soy: LOOOK IT'S THE BOTS NAME!!!!!
	"yuyuko":       "saigyouji_yuyuko",
	"sakuya":       "izayoi_sakuya",
	"flandre":      "flandre_scarlet",
	"remilia":      "remilia_scarlet",
	"patchouli":    "patchouli_knowledge",
	"cirno":        "cirno",
	"tenshi":       "hinanawi_tenshi",
	"meiling":      "hong_meiling",
	"rumia":        "rumia",
	"rinnosuke":    "morichika_rinnosuke",
	"murasa":       "murasa_minamitsu",
	"mamizou":      "futatuiwa_mamizou",
	"shou":         "toramaru_shou",
	"nemuno":       "sakata_nemuno",
	"eternity":     "eternity_larva",
	"narumi":       "yatadera_narumi",
	"daiyousei":    "daiyousei",
	"ringo":        "ringo_(touhou)",
	"kosuzu":       "motoori_kosuzu",
	"akyuu":        "hidea_no_akyuu",
	"hatate":       "himekaidou_hatate",
	"mima":         "mima_(touhou)", // whO?
	"sariel":       "sariel(touhou)",
	"yumemi":       "okazaki_yumemi",
	"shinki":       "shinki",
	"lily":         "lily_white",
	"jo'on":        "yorigami_jo'on",
	"shion":        "yorigami_shion", // the better of the two
	"seiran":       "seiran_(touhou)",
	"koakuma":      "koakuma",
	"raiko":        "horikawa_raiko", // i am going insane typing this list
	"okina":        "matara_okina",
	"mai":          "teireida_mai",
	"satono":       "nishida_satono",
	"aunn":         "komano_aun",
	"komachi":      "onozuka_komachi",
	"wakasagihime": "wakasagihime",
	"toyohime":     "watasuki_no_toyohime",
	"yorihime":     "watasuki_no_yorihime",
	"renko":        "usami_renko",
	"maribel":      "maribel_hearn",
	"nue":          "houjuu_nue",
	"iku":          "nagae_iku",
	"elly":         "elly_(touhou)",
	"kasen":        "ibaraki_kasen",
	"keine":        "kamishirasawa_keine", // i had a stroke typing this
	"konngara":     "konngara",
	"aya":          "shameimaru_aya",
	"nitori":       "kawashiro_nitori",
	"sumireko":     "usami_sumireko",
	"okuu":         "reiuji_utsuho",
	"koshi":        "komeiji_koishi",
	"mokou":        "fujiwara_no_mokou",
	"satori":       "komeiji_satori",
	"momiji":       "inubashiri_momiji",
	"ran":          "yakumo_ran",
	"kagerou":      "imaizumi_kagerou",
	"reisen":       "reisen_udongein_inaba",
	"rei'sen":      "reisen", // what an autism naming scheme
	"letty":        "letty_whiterock",
	"suwako":       "moriya_suwako",
	"shizuha":      "aki_shizuha",
	"sanae":        "kochiya_sanae", // le
	"clownpiece":   "clownpiece",
	"yukari":       "yakumo_yukari",
	"yuuka":        "kazami_yuuka",
	"suika":        "ibuki_suika",
	"sekibanki":    "sekibanki",
	"wriggle":      "wriggle_nightbug",
	"hina":         "kagiyama_hina",
	"alice":        "alice_margatroid",
	"kyouko":       "kasodani_kyouko",
	"kisume":       "kisume",
	"nazrin":       "nazrin",
	"sukuna":       "sukuna_shinmyoumaru",
	"kokoro":       "hata_no_kokoro",
	"yoshika":      "miyako_yoshika",
	"seiga":        "kaku_seiga",
	"kogasa":       "tatara_kogasa",
	"futo":         "mononobe_no_futo",
	"miko":         "toyosatomimi_no_miko",
	"tojiko":       "soga_no_tojiko",
	"mystia":       "mystia_lorelei",
	"genji":        "genji_(touhou)",
	"byakuren":     "hijiri_byakuren",
	"hecatia":      "hecatia_lapislazuli",
	"junko":        "junko_(touhou)",
	"sagume":       "kishin_sagume",
	"doremy":       "doremy_sweet",
	"minoriko":     "aki_minoriko",
	"yamame":       "kurodani_yamame",
	"yuugi":        "hoshiguma_yuugi",
	"parsee":       "mizuhasi_parsee",
	"tewi":         "inaba_tewi",
	"medicine":     "medicine_melancholy",
	"eiki":         "shinki_eiki",
	"orin":         "kaenbyou_rin",
	"kaguya":       "houraisan_kaguya",
	"eirin":        "yagokoro_eirin",
	"kanako":       "yasaka_kanako",
	"chen":         "chen",
	"star":         "star_sapphire",
	"luna":         "luna_child",
	"sunny":        "sunny_milk",
	"eika":         "ebisu_eika",
	"urumi":        "ushizaki_urumi",
	"kutaka":       "niwatari_kutaka",
	"lunasa":       "lunasa_prismriver",
	"lyrica":       "lyrica_prismriver",
	"merlin":       "merlin_prismriver",
	"keiki":        "haniyasu_keiki",
	"saki":         "kurokoma_saki",
	"mayumi":       "joutouguu_mayumi",
	"yachie":       "kicchou_yachie",
	"ichirin":      "kumoi_ichirin",
	"miyoi":        "okunoda_miyoi",
	"chiyuri":      "kitashira_kawa_chiyuri",
	"satsuki":      "satsuki_rin",
	"tokiko":       "tokiko_(touhou)",
	"mimi":         "mimi-chan",
	"kotohime":     "kotohime",
	"rikako":       "asakura_rikako",
	"ruukoto":      "ruukoto",
	"elis":         "elis_(touhou)",
	"ellen":        "ellen",
	"orange":       "orange_(touhou)",
	"benben":       "tsukomo_benben",
	"yatsuhashi":   "tsukumo_yatsuhashi",
	"mike":         "goutokuji_mike", // mee-kay not meye-kee or meyek
	"takane":       "yamashiro_takane",
	"sannyo":       "komakusa_sannyo",
	"chimata":      "tenkyuu_chimata",
	"tsukasa":      "kudamaki_tsukasa",
	"momoyo":       "himemushi_momoyo",
	"musumaru":     "tamatsukuri_misumaru",
	"youka":        "kazami_youka",
}

var characterlist string = "`"

func init() {
	for name := range characters {
		characterlist += (name + " ")
	}
	characterlist += "`"
}
